### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by Haroenv** [algolia/youtube-captions-scraper#5]
Hey! 

The person who maintained this at Algolia, @iam4x, is no longer working at Algolia and we aren't using it in production anymore. If someone would be interested in maintaining and publishing the package; that would be great!

cc @syzer, would you be interested?

**Comment by syzer** [comment]
Hehe.. just keep clicking merge :D
Currently bit busy with writing AI's
( take a look: https://auto.simpego.ch/en )
This one works only for Swiss one's

But if there's issue I can make PR for it.. but click [merge] is required on your part :D

**Comment by iam4x** [comment]
I guess @syzer is the right person with all the tests written, probably know better the project than me 👍

**Comment by imaynotbereal** [comment]
I'd like to contribute to this project. I have forked this project, git cloned the fork in my system and opened it in Webstorm. I'm trying to run test case, index.test.js and I get the below error:

"C:\Program Files\JetBrains\WebStorm 2018.2.1\bin\runnerw.exe" D:\gTools\node\node.exe D:\youtube\youtube-captions-scraper\test\index.test.js
D:\youtube\youtube-captions-scraper\test\index.test.js:1
(function (exports, require, module, __filename, __dirname) { import { test } from 'ava';
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)

Process finished with exit code 1

I need guidance in fixing this, guess I may be doing something.

**Comment by Haroenv** [comment]
How did you run the tests @imaynotbereal? It needs to be run with Ava, so `yarn test`  or `npm test` should be how it is invoked

**Comment by pcktlwyrcode** [comment]
I am currently working with this code. One thing I a want to do is adapt the output format so I can pipe it into another package which produces the various subtitle formats srt, vtt etc.. used in the business..
